package io.casehub.soc.domain;

public enum SocStepType {
    ALERT_TRIAGE,
    INCIDENT_PROMOTED,
    INVESTIGATION_STEP,
    CONTAINMENT_DECISION,
    CONTAINMENT_GATE_DECISION,
    CONTAINMENT_APPROVAL,
    CONTAINMENT_REJECTION,
    CONTAINMENT_EXECUTED,
    RECOVERY_VERIFIED,
    RECOVERY_DIVERGED,
    INCIDENT_RESOLVED
}
